pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub')  // Add in Jenkins > Credentials
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/Sanjeevroars/CI-CD-Devops.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t sanju716/myapp:latest .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push sanju716/myapp:latest
                    '''
                }
            }
        }

        stage('Deploy to AWS EC2') {
            steps {
                sshagent(['ec2-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@<ec2-public-ip> '
                        docker pull sanju716/myapp:latest &&
                        docker stop myapp || true &&
                        docker rm myapp || true &&
                        docker run -d -p 80:8080 --name myapp sanju716/myapp:latest'
                    '''
                }
            }
        }
    }
}
