pipeline {
    agent any

    environment {
        PYTHONPATH = "${WORKSPACE}"
        ART_USER = credentials('artifactory-username') // Add this in Jenkins
        ART_PASS = credentials('artifactory-password')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/Sanjeevroars/CI-CD-Devops.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r user-service/requirements.txt || poetry install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'cd user-service && pytest --junitxml=report.xml'
            }
        }

        stage('Build Package') {
            steps {
                sh 'cd user-service && python setup.py sdist bdist_wheel'
            }
        }

        stage('Publish to Artifactory') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'artifactory-credentials', usernameVariable: 'ART_USER', passwordVariable: 'ART_PASS')]) {
                    sh 'curl -u$ART_USER:$ART_PASS -T dist/*.whl "https://trial72qis4.jfrog.io/artifactory/python-local/"'
                }
            }
        }

    }

    post {
        always {
            node {
                junit 'report.xml'  // <- move this inside a node block
            }
        }
    }
}
